### ISSUE TITLE
مشکل راست به چپ.

### ISSUE THREAD

**Issue by alefvanoon** [Hameds/casper-hamed#1]
هنوز با قالب جدید هم وبلاگ چپ به راسته.
اگه می‌شه لطفا کدهای اینجکت شده رو هم روی گیت قرار بدید.

**Comment by Hameds** [comment]
<div dir='rtl'>
خدمت شما. البته من از فونت وزیر هم استفاده می‌کنم
</div>

```css
<link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v[X.Y.Z]/dist/font-face.css" rel="stylesheet" type="text/css" />
<style>
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{font-family:'Vazir'!important}body{text-align:right;direction:rtl}pre{text-align:left;direction:ltr}.site-nav-logo{margin-right:0;margin-left:32px}.site-nav-left{margin-right:0;margin-left:10px}.site-nav-left .nav li:last-of-type{padding-right:0;padding-left:20px}.nav-post-title.dash{left:auto;right:-25px}.site-nav-main .site-nav-left-wrapper:after{right:auto;left:0}.author-header-content{margin:5px 30px 0 0}.author-card .author-info{margin:0 20px 0 0}.subscribe-overlay button{margin:0 15px 0 0}.subscribe-form button{margin:0 10px 0 0}@media (min-width: 795px){.post-card-large .post-card-content-link,.post-card-large .post-card-meta{padding:0 40px 0 0}}.post-card-byline-content{margin:2px 6px 0 0}.static-avatar{margin:0 -6px 0 0}.post-full-byline-content .author-list{padding:0 0 0 12px}.author-list{margin:0 4px 0 0}.post-full-content blockquote{border-left:0;border-right:3px solid #3eb0ef}.site-footer-nav a{margin-left:0;margin-right:20px}.site-footer-nav a:before{left:auto;right:-11px}</style>

```
